// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTJob : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTJob GetRootAsDTJob(ByteBuffer _bb) { return GetRootAsDTJob(_bb, new DTJob()); }
  public static DTJob GetRootAsDTJob(ByteBuffer _bb, DTJob obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTJob __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Desc { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescArray() { return __p.__vector_as_array<byte>(6); }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
  public int RoleId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string HeadPic { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHeadPicBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetHeadPicBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetHeadPicArray() { return __p.__vector_as_array<byte>(12); }
  public string JobPic { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJobPicBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetJobPicBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetJobPicArray() { return __p.__vector_as_array<byte>(14); }
  public string JobDesc { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJobDescBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetJobDescBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetJobDescArray() { return __p.__vector_as_array<byte>(16); }
  public int Attack { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Defense { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hit { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Dodge { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Cri { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Res { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<YouYou.DataTable.DTJob> CreateDTJob(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset DescOffset = default(StringOffset),
      StringOffset NameOffset = default(StringOffset),
      int RoleId = 0,
      StringOffset HeadPicOffset = default(StringOffset),
      StringOffset JobPicOffset = default(StringOffset),
      StringOffset JobDescOffset = default(StringOffset),
      int Attack = 0,
      int Defense = 0,
      int Hit = 0,
      int Dodge = 0,
      int Cri = 0,
      int Res = 0) {
    builder.StartTable(13);
    DTJob.AddRes(builder, Res);
    DTJob.AddCri(builder, Cri);
    DTJob.AddDodge(builder, Dodge);
    DTJob.AddHit(builder, Hit);
    DTJob.AddDefense(builder, Defense);
    DTJob.AddAttack(builder, Attack);
    DTJob.AddJobDesc(builder, JobDescOffset);
    DTJob.AddJobPic(builder, JobPicOffset);
    DTJob.AddHeadPic(builder, HeadPicOffset);
    DTJob.AddRoleId(builder, RoleId);
    DTJob.AddName(builder, NameOffset);
    DTJob.AddDesc(builder, DescOffset);
    DTJob.AddId(builder, Id);
    return DTJob.EndDTJob(builder);
  }

  public static void StartDTJob(FlatBufferBuilder builder) { builder.StartTable(13); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddDesc(FlatBufferBuilder builder, StringOffset DescOffset) { builder.AddOffset(1, DescOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(2, NameOffset.Value, 0); }
  public static void AddRoleId(FlatBufferBuilder builder, int RoleId) { builder.AddInt(3, RoleId, 0); }
  public static void AddHeadPic(FlatBufferBuilder builder, StringOffset HeadPicOffset) { builder.AddOffset(4, HeadPicOffset.Value, 0); }
  public static void AddJobPic(FlatBufferBuilder builder, StringOffset JobPicOffset) { builder.AddOffset(5, JobPicOffset.Value, 0); }
  public static void AddJobDesc(FlatBufferBuilder builder, StringOffset JobDescOffset) { builder.AddOffset(6, JobDescOffset.Value, 0); }
  public static void AddAttack(FlatBufferBuilder builder, int Attack) { builder.AddInt(7, Attack, 0); }
  public static void AddDefense(FlatBufferBuilder builder, int Defense) { builder.AddInt(8, Defense, 0); }
  public static void AddHit(FlatBufferBuilder builder, int Hit) { builder.AddInt(9, Hit, 0); }
  public static void AddDodge(FlatBufferBuilder builder, int Dodge) { builder.AddInt(10, Dodge, 0); }
  public static void AddCri(FlatBufferBuilder builder, int Cri) { builder.AddInt(11, Cri, 0); }
  public static void AddRes(FlatBufferBuilder builder, int Res) { builder.AddInt(12, Res, 0); }
  public static Offset<YouYou.DataTable.DTJob> EndDTJob(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTJob>(o);
  }
};


}
