// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTRoleList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTRoleList GetRootAsDTRoleList(ByteBuffer _bb) { return GetRootAsDTRoleList(_bb, new DTRoleList()); }
  public static DTRoleList GetRootAsDTRoleList(ByteBuffer _bb, DTRoleList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTRoleList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTRole? DTRoles(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTRole?)(new YouYou.DataTable.DTRole()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTRolesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTRoleList> CreateDTRoleList(FlatBufferBuilder builder,
      VectorOffset DTRolesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTRoleList.AddDTRoles(builder, DTRolesOffset);
    return DTRoleList.EndDTRoleList(builder);
  }

  public static void StartDTRoleList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTRoles(FlatBufferBuilder builder, VectorOffset DTRolesOffset) { builder.AddOffset(0, DTRolesOffset.Value, 0); }
  public static VectorOffset CreateDTRolesVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRole>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTRolesVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRole>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTRolesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTRoleList> EndDTRoleList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTRoleList>(o);
  }
};


}
